// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkwyvwmpnosrurozsbrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrd3l2d21wbm9zcnVyb3pzYnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjQ2MjQsImV4cCI6MjA3NDU0MDYyNH0.AXU-GAE7Dq4BwYvFy13d-7cqcXlGitinqcqIa687tzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});